version: '2'
services:
  redis:
    image: redis:4.0
    container_name: myredis
    # command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - "./datadir:/redis/data"
      - "./resources/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass 123456
